package main

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"text/tabwriter"

	"github.com/spf13/cobra"

	"github.com/Warewave-Technology/postern/internal/auth"
	"github.com/Warewave-Technology/postern/internal/config"
	"github.com/Warewave-Technology/postern/internal/store"
)

/*
 * newAdminCmd, postern'in KENDİ yönetici kapısı.
 *
 * NEDEN VAR: postern'e girmenin iki yolu vardı ve ikisi de dışarıya
 * bağımlıydı — SSH açık anahtarı ya da bir OIDC sağlayıcısı. Dizini olan
 * ama kimlik sağlayıcısı OLMAYAN bir kurum paneli hiç açamıyordu. İlk
 * yöneticiyi ürünün kendisi verebilmeli.
 *
 * ⚠️ YETKİ MODELİ DEĞİŞMEDİ: is_admin YALNIZCA buradan, yani host
 * üzerinden veriliyor. Bu komut o kuralın istisnası değil, tam olarak
 * uygulandığı yer.
 */
func newAdminCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "admin",
		Short: "Manage postern's own administrator accounts",
	}
	cmd.AddCommand(newAdminBootstrapCmd())
	cmd.AddCommand(newAdminIssueCmd())
	cmd.AddCommand(newAdminListCmd())
	cmd.AddCommand(newAdminRevokeCmd())
	return cmd
}

func newAdminBootstrapCmd() *cobra.Command {
	var configPath, name, osUser, email string

	cmd := &cobra.Command{
		Use:   "bootstrap",
		Short: "Create the break-glass administrator and print its sign-in secret once",
		Long: "Creates a postern administrator that can sign in to the panel without an " +
			"identity provider.\n\n" +
			"This account is NOT temporary scaffolding. It is the way back in: " +
			"switching the sign-in source to a directory or an identity provider leaves " +
			"it in place, and if that source ever stops answering, this account plus\n" +
			"  postern settings set --key auth.source --value local\n" +
			"is how anyone gets in at all. Keep its secret the way you keep a root " +
			"password.\n\n" +
			"The secret is generated by postern and printed once. You cannot choose it: " +
			"a value a human picks is a value a human reuses, and the one credential this " +
			"product must never hold is the user's corporate password.",
		RunE: func(cmd *cobra.Command, args []string) error {
			/*
			 * ⚠️ ADIN VARSAYILANI VAR.
			 *
			 * --name zorunluyken operatör o an bir ad uydurmak zorunda
			 * kalıyordu ve uydurulan ad ("kurulum", "setup", "temp")
			 * hesabın GEÇİCİ olduğu izlenimini veriyordu. Oysa bu hesap
			 * kalıcı: kaynağı değiştirmek onu yerinde bırakıyor ve
			 * dizin çöktüğünde tek giriş yolu o.
			 *
			 * "admin" tahmin edilmesi kolay bir ad — ve sorun değil:
			 * giriş 120 bitlik makine üretimi bir sır istiyor, hız
			 * sınırı var, ve hesabın varlığı yanlış sırda bile
			 * sızdırılmıyor (bkz. locallogin.go). Adın gizliliği bir
			 * savunma değil.
			 */
			if name == "" {
				name = "admin"
			}
			if osUser == "" {
				osUser = name
			}

			cfg, err := config.Load(configPath)
			if err != nil {
				return err
			}
			ctx := context.Background()

			db, err := store.Open(ctx, cfg.Database.DSN)
			if err != nil {
				return err
			}
			defer db.Close()

			out := cmd.OutOrStdout()

			/*
			 * ⚠️ VAR OLAN HESABIN SIRRI SESSİZCE DEĞİŞMEZ.
			 *
			 * Komutu ikinci kez çalıştıran operatör ekranda yeni bir sır
			 * görür ve elindekinin çöpe gittiğini fark etmez. Daha
			 * kötüsü: bu yolla kurulumun tek yöneticisinin kimlik
			 * bilgisi döndürülebilirdi. Var olan hesap için komut
			 * DURUYOR ve ne yapılacağını söylüyor.
			 *
			 * Kontrol harf duyarsız: "Ops" yazıp ikinci bir yönetici
			 * (ve ikinci bir canlı sır) yaratmak, düzeltilmesi zor ve
			 * fark edilmesi zor bir hata olurdu.
			 */
			if existing, err := db.UserByNameFold(ctx, name); err == nil {
				// ⚠️ Mesaj ÇALIŞAN bir yol göstermeli. İlk hâli
				// yalnızca `revoke` diyordu ve bu bir çıkmaz sokaktı:
				// revoke hesabı bırakıyor, bootstrap var olan hesabı
				// reddediyor, operatör iki komut arasında sıkışıyordu.
				// Gerçek akışı çalıştırmadan fark edilmedi.
				return fmt.Errorf(
					"account %q already exists (you asked for %q): bootstrap only "+
						"creates new accounts — to give this one a secret use "+
						"`postern admin issue --name %s`, and if it already has one, "+
						"`postern admin revoke --name %s` first",
					existing, name, existing, existing)
			} else if !errors.Is(err, store.ErrNotFound) {
				return err
			}

			secret, verifier, err := auth.NewLocalSecret()
			if err != nil {
				return err
			}

			if _, err := db.CreateUser(ctx, name, email, osUser); err != nil {
				return err
			}
			if err := db.AddLocalCredential(ctx, name, verifier, "cli"); err != nil {
				return err
			}
			if err := db.SetUserAdmin(ctx, name, true); err != nil {
				return err
			}

			// ⚠️ DENETİM SATIRI SIRRI İÇERMEZ. Yalnızca "böyle bir kapı
			// açıldı" bilgisi; değerin kendisi hiçbir kalıcı yere
			// yazılmıyor.
			if err := db.LogAdmin(ctx, store.AdminLogEntry{
				Actor: "cli", Via: "cli", Action: "admin.bootstrap", Entity: name,
				Details: "local administrator created with a generated secret",
			}); err != nil {
				return err
			}

			fmt.Fprintf(out, "Administrator %q created.\n\n", name)
			fmt.Fprintf(out, "  sign-in secret:  %s\n\n", secret)
			fmt.Fprint(out, "This is the only time it is shown. postern stores a verifier, "+
				"not the secret,\nand cannot print it again. Put it in a password manager now.\n\n")
			/*
			 * ⚠️ BU CÜMLE BİR ÇIKMAZ SOKAK GÖSTERİYORDU — ve aynı
			 * dosyanın 108. satırındaki hata metni o çıkmazı zaten
			 * anlatıyor. "revoke edip yeniden bootstrap et" işlemiyor:
			 * revoke hesabı BIRAKIYOR, bootstrap var olan hesabı
			 * reddediyor. Üstelik bu yolu yalnızca ZATEN kilitlenmiş
			 * bir operatör yürüyor.
			 */
			fmt.Fprintf(out, "If you lose it, run `postern admin revoke --name %s` "+
				"then `postern admin issue --name %s`.\n\n", name, name)
			/*
			 * ⚠️ HESABIN NE OLDUĞU BURADA YAZMALI.
			 *
			 * Yazmadığında operatör ona geçici bir ad veriyor ve
			 * kurulumdan sonra ne yapacağını bilemiyor. Oysa cevabı
			 * var: hiçbir şey. Kalıcı, ve dizin çöktüğü gün tek giriş
			 * yolu.
			 */
			fmt.Fprint(out, "This account is permanent. Switching the panel to a directory "+
				"or an identity\nprovider leaves it in place but closes its door; if that "+
				"source stops answering,\n")
			fmt.Fprint(out, "  postern settings set --key auth.source --value local\n")
			fmt.Fprint(out, "opens it again and this secret still works.\n")
			return nil
		},
	}

	cmd.Flags().StringVar(&configPath, "config", "postern.yaml", "path to the config file")
	cmd.Flags().StringVar(&name, "name", "",
		"postern username for the administrator (defaults to \"admin\")")
	cmd.Flags().StringVar(&osUser, "os-user", "", "account name on targets (defaults to --name)")
	cmd.Flags().StringVar(&email, "email", "", "optional email")
	return cmd
}

/*
 * newAdminIssueCmd, VAR OLAN bir hesaba yerel sır verir.
 *
 * bootstrap'tan farkı: hesap açmıyor. Var olma sebebi kurtarma yolu —
 * tek yöneticinin sırrı kaybolduğunda `revoke` + `issue` ikilisi onu
 * geri getiriyor. Bu komut olmadan operatörün elinde yalnızca "ikinci
 * bir yönetici hesabı aç" kalıyordu ve kurulumlarda ops, ops2, ops3
 * birikiyordu.
 *
 * ⚠️ is_admin'e DOKUNMUYOR. Var olan bir hesaba sır vermek ile o hesabı
 * yönetici yapmak ayrı iki karar; ikincisini sessizce yapmak, bir SSO
 * kullanıcısına farkında olmadan yönetici yetkisi vermek olurdu.
 */
func newAdminIssueCmd() *cobra.Command {
	var configPath, name string

	cmd := &cobra.Command{
		Use:   "issue",
		Short: "Issue a local sign-in secret to an existing account",
		RunE: func(cmd *cobra.Command, args []string) error {
			if name == "" {
				return errors.New("--name is required")
			}
			cfg, err := config.Load(configPath)
			if err != nil {
				return err
			}
			ctx := context.Background()

			db, err := store.Open(ctx, cfg.Database.DSN)
			if err != nil {
				return err
			}
			defer db.Close()

			u, err := db.User(ctx, name)
			if err != nil {
				return err
			}

			secret, verifier, err := auth.NewLocalSecret()
			if err != nil {
				return err
			}
			// AddLocalCredential üstüne yazmıyor: var olan sır bu yoldan
			// da sessizce değişemez.
			if err := db.AddLocalCredential(ctx, u.Name, verifier, "cli"); err != nil {
				if errors.Is(err, store.ErrCredentialExists) {
					return fmt.Errorf(
						"account %q already holds a secret: run "+
							"`postern admin revoke --name %s` first", u.Name, u.Name)
				}
				return err
			}
			if err := db.LogAdmin(ctx, store.AdminLogEntry{
				Actor: "cli", Via: "cli", Action: "admin.issue_local", Entity: u.Name,
				Details: "local sign-in secret issued to an existing account",
			}); err != nil {
				return err
			}

			out := cmd.OutOrStdout()
			fmt.Fprintf(out, "Secret issued for %q (admin: %t).\n\n", u.Name, u.Admin)
			fmt.Fprintf(out, "  sign-in secret:  %s\n\n", secret)
			fmt.Fprint(out, "This is the only time it is shown.\n")
			if !u.Admin {
				/*
				 * ⚠️ SIRADAN HESAPTA BU DEĞER GEÇİCİ ve operatör bunu
				 * bilmeli.
				 *
				 * Kural store'da: yönetici olmayan bir hesaba verilen
				 * kimlik bilgisi "değiştirilmek zorunda" doğuyor, çünkü
				 * onu VEREN de biliyor. Komut bunu söylemezse, operatör
				 * değeri kalıcı sanıp bir kasaya koyar ve kişi ilk
				 * girişte değiştirince o kayıt sessizce ölür.
				 */
				fmt.Fprint(out, "\nThis account is not an administrator, so the value is "+
					"TEMPORARY: they must set their own password at their first "+
					"sign-in, and this secret stops working then. Do not file it.\n")
				fmt.Fprint(out, "\nIf you meant to make them an administrator, use "+
					"`postern user modify --name "+u.Name+" --admin=true` — note that "+
					"doing so drops any password they hold, because an administrator's "+
					"credential has to come from this host.\n")
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&configPath, "config", "postern.yaml", "path to the config file")
	cmd.Flags().StringVar(&name, "name", "", "postern username")
	return cmd
}

/*
 * newAdminListCmd, yerel kimlik bilgisi olan hesapları listeler.
 *
 * ⚠️ GÖRÜNÜRLÜK BİR GÜVENLİK ÖZELLİĞİ. Bu hesaplar bir acil durum kapısı
 * ve kullanılmayan bir acil durum kapısı unutulmuş bir kapıdır.
 * Operatörün "kimlerde var, en son ne zaman kullanıldı" sorusunu
 * veritabanına girmeden cevaplayabilmesi gerekiyor.
 */
func newAdminListCmd() *cobra.Command {
	var configPath string

	cmd := &cobra.Command{
		Use:   "list",
		Short: "List accounts that hold a local sign-in secret",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(configPath)
			if err != nil {
				return err
			}
			ctx := context.Background()

			db, err := store.Open(ctx, cfg.Database.DSN)
			if err != nil {
				return err
			}
			defer db.Close()

			holders, err := db.LocalCredentialHolders(ctx)
			if err != nil {
				return err
			}
			if len(holders) == 0 {
				fmt.Fprintln(cmd.OutOrStdout(), "no account holds a local secret")
				return nil
			}

			w := tabwriter.NewWriter(cmd.OutOrStdout(), 0, 0, 2, ' ', 0)
			fmt.Fprintln(w, "USERNAME\tADMIN\tKIND\tSTATE\tCREATED\tBY\tLAST USED")
			for _, h := range holders {
				last := "never"
				if !h.LastUsedAt.IsZero() {
					last = h.LastUsedAt.Format("2006-01-02 15:04")
				}
				/*
				 * ⚠️ TÜR SÜTUNU BİR TEŞHİS ARACI.
				 *
				 * "Neden giremiyor" sorusunun cevabı çoğu zaman burada:
				 * hesap "issued (must change)" hâlindeyse kişi giriyor
				 * ama paneli açamıyor, çünkü önce parolasını koyması
				 * gerekiyor. Bu ayrımı göstermeyen bir liste, operatörü
				 * olmayan bir arızayı aramaya gönderir.
				 */
				kind := "secret"
				switch {
				case h.Chosen:
					kind = "password"
				case h.MustChange:
					kind = "issued (must change)"
				}
				fmt.Fprintf(w, "%s\t%t\t%s\t%s\t%s\t%s\t%s\n",
					h.Username, h.IsAdmin, kind, h.State,
					h.CreatedAt.Format("2006-01-02"), h.CreatedBy, last)
			}
			return w.Flush()
		},
	}
	cmd.Flags().StringVar(&configPath, "config", "postern.yaml", "path to the config file")
	return cmd
}

// newAdminRevokeCmd, yerel kimlik bilgisini kaldırır. Hesap ve denetim
// izi durur — kaldırılan yalnızca giriş yolu.
func newAdminRevokeCmd() *cobra.Command {
	var configPath, name string

	cmd := &cobra.Command{
		Use:   "revoke",
		Short: "Remove an account's local sign-in secret",
		RunE: func(cmd *cobra.Command, args []string) error {
			if name == "" {
				return errors.New("--name is required")
			}
			cfg, err := config.Load(configPath)
			if err != nil {
				return err
			}
			ctx := context.Background()

			db, err := store.Open(ctx, cfg.Database.DSN)
			if err != nil {
				return err
			}
			defer db.Close()

			if err := db.RemoveLocalCredential(ctx, name); err != nil {
				return err
			}
			if err := db.LogAdmin(ctx, store.AdminLogEntry{
				Actor: "cli", Via: "cli", Action: "admin.revoke_local", Entity: name,
				Details: "local sign-in secret removed",
			}); err != nil {
				return err
			}
			fmt.Fprintf(cmd.OutOrStdout(),
				"Local secret for %q removed. The account and its audit trail remain.\n",
				strings.TrimSpace(name))
			return nil
		},
	}
	cmd.Flags().StringVar(&configPath, "config", "postern.yaml", "path to the config file")
	cmd.Flags().StringVar(&name, "name", "", "postern username")
	return cmd
}
