-- 003_admin: uygulama yönetim yetkisi.
--
-- is_admin, ROL değil SÜTUN: roller hedef-erişim yetkisidir ve öyle
-- kalmalı. "admin" adında sihirli bir rol aramak, o adla rol açan herkesi
-- farkında olmadan yetki dağıtır yapardı. Sütun ise tek anlamlıdır ve
-- user list çıktısında tek bakışta denetlenir.
--
-- Yetki modeli (S3 sözleşmesinin devamı): bu bayrağı yalnızca bastion
-- hostundaki CLI değiştirir (user modify --admin). Web/API tarafı bayrağı
-- OKUR, değiştiremez — kendini admin yapabilen bir admin paneli, panel
-- ele geçirildiğinde kalıcı yetki demek olurdu.
--
-- BOOLEAN, 0/1 INTEGER değil: Go tarafı bunu bool olarak yazıyor ve
-- PostgreSQL boolean parametresini integer sütuna kabul etmez.
ALTER TABLE users ADD COLUMN is_admin BOOLEAN NOT NULL DEFAULT FALSE;
