-- 008_sso_only: erişimin IdP'ye bağlı kalmasını zorunlu kılan bayrak.
--
-- Kapatılan boşluk: postern'de iki giriş kapısı var ve public key kapısı
-- IdP'ye hiç bakmıyor. Kullanıcı IdP'de silinse bile anahtarı çalışmaya
-- devam ederdi — "orada silinince erişim biter" varsayımını sessizce
-- yalanlayan bir durum. Aynı boşluk yetkinin TAZELİĞİ için de geçerli:
-- anahtarla giren kullanıcının rolleri senkronize edilmez.
--
-- JIT ile doğan kullanıcılar sso_only=TRUE doğar. Elle oluşturulan servis
-- hesapları (otomasyon, CI) FALSE kalır ve anahtarla girmeye devam eder —
-- ki bu doğru davranış: onların IdP'de karşılığı yok.
ALTER TABLE users ADD COLUMN sso_only BOOLEAN NOT NULL DEFAULT FALSE;
